<?php
session_start();

if (!isset($_SESSION['user_id'])) {
    $pageTitle = "Login Required";
    ob_start();
    echo <<< _MESSAGE
    <div class="login-warning">
        <h2>❌ Access Denied</h2>
        <p>Please log in to perform a search.</p>
        <p><a href="login_user.php" class="btn">Log in</a> or <a href="index.php" class="btn"> Return Home</a></p>
    </div>
    _MESSAGE;
    $pageContent = ob_get_clean();
    include './features/base_layout.php';
    exit;
}

require_once 'db/db_connection.php';
$user_id = $_SESSION['user_id'] ?? null;

function show_error_page($message) {
    $pageTitle = "Error";
    ob_start();
    echo <<< _ERROR
    <div class="error-message">
        <h2>Something went wrong</h2>
        <p>$message</p>
        <p><a href="search_form.php" class="btn">🔍 Try Again</a></p>
    </div>
    _ERROR;
    $pageContent = ob_get_clean();
    include './features/base_layout.php';
    exit;
}

// Collect and validate inputs
$protein = $_POST['protein'];
$taxon = $_POST['taxon'];
$limit = $_POST['limit'] ?? 10;
$min_len = isset($_POST['use_length_filter']) ? (int)$_POST['min_len'] : 0;
$max_len = isset($_POST['use_length_filter']) && $_POST['max_len'] !== '' ? (int)$_POST['max_len'] : 100000;

if ($min_len > $max_len) {
    show_error_page("Minimum sequence length cannot be greater than maximum length.");
}

$run_id = uniqid("run_");

// Run python search script
$cmd = escapeshellcmd("python3 scripts/new_get_sequences.py \"$protein\" \"$taxon\" $limit $min_len $max_len $run_id");
$output = shell_exec($cmd);
// echo "<h3>Python Output:</h3><pre>$output</pre>";

// Parse result to CSV
$csv_path = "scripts/output/$run_id/sequences.csv";
if (!file_exists($csv_path)) {
    show_error_page("No sequences were found for this query. Try changing your parameters.");
}

$csv_data = array_map('str_getcsv', file($csv_path));
array_shift($csv_data); // Remove header

// Store query in database
$query_sql = "INSERT INTO Queries (search_id, user_id, protein_family, taxon, min_len, max_len, no_of_sequences)
              VALUES (?, ?, ?, ?, ?, ?, ?)";
$stmt = $pdo->prepare($query_sql);
$stmt->execute([$run_id, $user_id, $protein, $taxon, $min_len, $max_len, count($csv_data)]);

// Store sequences in database
$seq_sql = "INSERT INTO Sequences (refseq_id, search_id, species, sequence) VALUES (?, ?, ?, ?)";
$seq_stmt = $pdo->prepare($seq_sql);
foreach ($csv_data as $row) {
    [$refseq_id, $species, $sequence, $description] = $row;
    $seq_stmt->execute([$refseq_id, $run_id, $species, $sequence]);
}

// Prepare page content
ob_start();
echo "<div class='content-container'>";
echo "<h1>✅ Protein Search Complete</h1>";
echo "<p>Here are the results for your search on <strong>$protein</strong> proteins in <strong>$taxon</strong>.</p>";

echo "<h2>Sequences Retrieved</h2>";
echo "<p><strong>Total:</strong> " . count($csv_data) . "</p>";
echo "<table border='1' cellpadding='6'>
<tr><th>RefSeq ID</th><th>Species</th><th>Length</th><th>Description</th></tr>";
foreach ($csv_data as $row) {
    [$refseq_id, $species, $sequence, $description] = $row;
    $length = strlen($sequence);
    echo "<tr>
        <td>$refseq_id</td>
        <td>$species</td>
        <td>$length</td>
        <td>$description</td>
    </tr>";
}
echo "</table>";
echo "<p><a href='scripts/output/$run_id/sequences.fasta' download>⬇️ Download FASTA</a></p>";

// Run ClustalO
echo "<h2>Clustal Omega Outputs</h2>";
$input_fasta = "scripts/output/$run_id/sequences.fasta";
$alignment_out = "scripts/output/$run_id/alignment.aln";
$distmat_out = "scripts/output/$run_id/identity_matrix.txt";
$tree_out = "scripts/output/$run_id/guide_tree.dnd";

$clustalo_cmd = escapeshellcmd("bash scripts/run_clustalo.sh \"$input_fasta\" \"$alignment_out\" \"$distmat_out\" \"$tree_out\"");
$clustalo_output = shell_exec($clustalo_cmd);

echo "<pre>$clustalo_output</pre>";

// Store analysis outpus in database
$insert_analysis = $pdo->prepare("INSERT INTO Analyses (search_id, type, result_path, label, file_type) VALUES (?, ?, ?, ?, ?)");

// Helper to do it in one line for later
function add_analysis($pdo, $run_id, $type, $path, $label)
{
    $ext = pathinfo($path, PATHINFO_EXTENSION);
    global $insert_analysis;
    $insert_analysis->execute([$run_id, $type, $path, $label, $ext]);
}

// Save each result into the DB
if (file_exists($alignment_out)) {
    add_analysis($pdo, $run_id, 'clustalo', $alignment_out, 'ClustalO alignment file');
}
if (file_exists($distmat_out)) {
    add_analysis($pdo, $run_id, 'clustalo', $distmat_out, 'Sequence identity matrix');
}
if (file_exists($tree_out)) {
    add_analysis($pdo, $run_id, 'clustalo', $tree_out, 'ClustalO guide tree (Newick format)');
}

echo "<h3>ClustalO Guide Tree</h3>";
echo "<p>This is a <strong>guide tree</strong> based on sequence similarity generated by Clustal Omega. It provides a visual approximation of sequence relationships, but it's not a true phylogenetic tree.</p>";
echo '<script src="https://cdnjs.cloudflare.com/ajax/libs/raphael/2.3.0/raphael.min.js" integrity="sha512-tBzZQxySO5q5lqwLWfu8Q+o4VkTcRGOeQGVQ0ueJga4A1RKuzmAu5HXDOXLEjpbKyV7ow9ympVoa6wZLEzRzDg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>';
echo "<script src='assets/js/jsphylosvg-min.js'></script>";
echo "<div id='phylo_tree' style='width: 100%; height: 600px; border: 1px solid #ccc; padding: 10px; margin-bottom: 20px;'></div>";

if (file_exists($tree_out)) {
    $tree_data = trim(preg_replace('/\s+/', '', file_get_contents($tree_out)));
    $escaped_tree = htmlspecialchars($tree_data, ENT_QUOTES);
    echo "
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            var newick = '$escaped_tree';
            new Smits.PhyloCanvas(
                newick,
                'phylo_tree',
                800,
                600,
                'rectangular'
            );
        });
    </script>";
} else {
    echo "<p style='color:red;'>No guide tree file found at $tree_out</p>";
}

// Plotcon analysis
echo "<h2>📈 Plotcon - Conservation Plot</h2>";
$plotcon_out_base = "scripts/output/$run_id/conservation";
$plotcon_img = $plotcon_out_base . ".1.png"; // This is what plotcon generates by default

$plotcon_cmd = escapeshellcmd("bash scripts/run_plotcon.sh \"$alignment_out\" \"$plotcon_out_base\"");
$plotcon_output = shell_exec($plotcon_cmd);

// echo "<h3>Plotcon Output:</h3><pre>$plotcon_output</pre>";

// If the image was generated successfully
if (file_exists($plotcon_img)) {
    // Save to database
    add_analysis($pdo, $run_id, 'plotcon', $plotcon_img, 'Conservation plot (plotcon)');

    // Display image on page
    echo "<h3>Conservation Plot</h3>";
    echo "<img src='$plotcon_img' style='max-width: 100%; border: 1px solid #ccc; padding: 10px;'>";
    echo "<p><a href='$plotcon_img' download>⬇️ Download Conservation Plot</a></p>";
} else {
    echo "<p style='color:red;'>Plotcon image not found at: $plotcon_img</p>";
}

// Identity Matrix Plot
$identity_img = "scripts/output/$run_id/identity_matrix.png";
$cmd = escapeshellcmd("python3 scripts/plot_identity_matrix_simple.py \"$run_id\" \"$protein\" \"$taxon\" " . count($csv_data));
$plot_output = shell_exec($cmd);

// Add to database
if (file_exists($identity_img)) {
    add_analysis($pdo, $run_id, 'identity_matrix', $identity_img, 'Sequence Identity Matrix (plot)');
    echo "<h3>Identity Matrix for each sequence</h3>";
    echo "<img src='$identity_img' style='max-width: 100%; border: 1px solid #ccc; padding: 10px;'>";
    echo "<p><a href='$identity_img' download>⬇️ Download Identity Matrix image</a></p>";
} else {
    echo "<p style='color:red;'>Identity matrix plot not found at $identity_img</p>";
}

// Run patmatmotifs to identify motifs in sequences using EMBOSS
echo "<h2>Motif Analysis</h2>";

// Construct and execute shell command to run the motif script
$motif_script = escapeshellcmd("bash scripts/new_run_patmatmotifs.sh \"$input_fasta\" \"$run_id\"");
shell_exec($motif_script);

// Path to the resulting TSV file
$motif_tsv = "scripts/output/$run_id/motif_results.tsv";

// Proceed only if the TSV exists
if (file_exists($motif_tsv)) {

    // Get a map of RefSeq IDs to internal DB sequence IDs (and species)
    $stmt = $pdo->prepare("SELECT id, refseq_id, species FROM Sequences WHERE search_id = ?");
    $stmt->execute([$run_id]);

    // Build PHP associative array: refseq_id => [id, species]
    $map = [];
    foreach ($stmt->fetchAll(PDO::FETCH_ASSOC) as $row) {
        $map[$row['refseq_id']] = [
            'id' => $row['id'],
            'species' => $row['species']
        ];
    }

    // Prepare SQL insert statement for motif hits
    $insert_motif = $pdo->prepare("
        INSERT INTO Motifs (search_id, sequence_id, prosite_id, motif_name, start_pos, end_pos)
        VALUES (?, ?, ?, ?, ?, ?)
    ");

    $inserted = 0;
    $parsed_motifs = []; // Store valid hits for displaying as HTML table

    // Read and parse the TSV
    $fh = fopen($motif_tsv, 'r');
    while (($line = fgetcsv($fh, 0, "\t")) !== false) {
        if (count($line) < 5) continue;

        [$refseq, $prosite, $name, $start, $end] = $line;
        $refseq = trim($refseq);

        // Make sure this RefSeq ID exists in the mapping
        if (isset($map[$refseq])) {
            $seq_id = $map[$refseq]['id'];
            $species = $map[$refseq]['species'];

            // Insert the motif hit into the Motifs table
            $insert_motif->execute([$run_id, $seq_id, $prosite, $name, $start, $end]);
            $inserted++;

            // Add to in-memory array to render HTML table later
            $parsed_motifs[] = [
                'refseq_id' => $refseq,
                'species' => $species,
                'motif_name' => $name,
                'start' => $start,
                'end' => $end
            ];
        }
    }
    fclose($fh);

    // Report how many motifs were found
    if ($inserted > 0) {
        echo "<p>✅ Found <strong>$inserted</strong> motif hits for sequences.</p>";

        // Display a table of motif hits (RefSeq ID, Species, Motif, Start, End)
        echo "<table border='1' cellpadding='6'>
        <tr><th>RefSeq ID</th><th>Species</th><th>Motif Name</th><th>Start</th><th>End</th></tr>";
        foreach ($parsed_motifs as $m) {
            echo "<tr>
                <td>{$m['refseq_id']}</td>
                <td>{$m['species']}</td>
                <td>{$m['motif_name']}</td>
                <td>{$m['start']}</td>
                <td>{$m['end']}</td>
            </tr>";
        }
        echo "</table>";

        // Record the TSV file in the Analyses table
        add_analysis($pdo, $run_id, 'motif', $motif_tsv, 'Motif results TSV');

        // Show download link
        echo "<p><a href='$motif_tsv' download>⬇️ Download Motif TSV</a></p>";
    } else {
        // No valid motif hits found
        echo "<p>⚠️ No motif hits were found for these sequences.</p>";
    }
}

// Motif Frequency Plot
// Query motif frequencies for this search run (how many times each motif appeared)
$freq_sql = "SELECT motif_name, COUNT(*) as count FROM Motifs WHERE search_id = ? GROUP BY motif_name";
$stmt = $pdo->prepare($freq_sql);
$stmt->execute([$run_id]);
$motif_freq = $stmt->fetchAll(PDO::FETCH_ASSOC);

// Write the frequencies into a temporary CSV file to be used for plotting
$freq_csv = "scripts/output/$run_id/motif_freq.csv";
$fp = fopen($freq_csv, 'w');

// Add header row to CSV
fputcsv($fp, ['motif_name', 'count']);

// Add each motif and its count
foreach ($motif_freq as $row) {
    fputcsv($fp, [$row['motif_name'], $row['count']]);
}
fclose($fp); // Done writing

// Call the Python script to generate a bar plot from the CSV data
$plot_cmd = escapeshellcmd("python3 scripts/plot_motif_freq_from_csv.py \"$run_id\" \"$freq_csv\" \"$protein\" \"$taxon\"");
shell_exec($plot_cmd);

// Display the resulting image on the page (if it was created successfully)
$plot_path = "scripts/output/$run_id/motif_frequency.png";
if (file_exists($plot_path)) {
    // Store image in database under Analyses table
    add_analysis($pdo, $run_id, 'motif', $plot_path, 'Motif frequency plot');

    // Display the image and download option
    echo "<h2>📊 Motif Frequency Bar Chart</h2>";
    echo "<img src='$plot_path' style='max-width:100%; height:auto; border:1px solid #ccc; padding:10px;'>";
    echo "<p><a href='$plot_path' download>⬇️ Download Frequency Bar chart</a></p>";
}

// Overall analyses table
echo "<h2>📂 Analysis Files</h2>";

$analysis_sql = "SELECT type, label, result_path, file_type, created_at FROM Analyses WHERE search_id = ?";
$stmt = $pdo->prepare($analysis_sql);
$stmt->execute([$run_id]);
$rows = $stmt->fetchAll(PDO::FETCH_ASSOC);

if ($rows) {
    echo "<table border='1' cellpadding='6'>
    <tr><th>Type</th><th>Description</th><th>Download</th><th>Created</th></tr>";
    foreach ($rows as $r) {
        $filename = basename($r['result_path']);
        echo "<tr>
            <td>{$r['type']}</td>
            <td>{$r['label']}</td>
            <td><a href='{$r['result_path']}' download='$filename'>Download</a></td>
            <td>{$r['created_at']}</td>
        </tr>";
    }
    echo "</table>";
} else {
    echo "<p>No analysis files found.</p>";
}

echo <<< _EXTRAS
<div class='external-links'>
    <h2>🔗 Next Steps & Other Useful Tools</h2>
    <p>Now that you've generated and downloaded your results, you might want to continue your analysis using external databases:</p>
    <ul>
        <li>
            <a href="https://www.uniprot.org/" target="_blank">UniProt</a> — Search for your proteins or sequences to find functional annotations, domain info, and cross-references to other databases.
        </li>
        <li>
            <a href="https://prosite.expasy.org/" target="_blank">PROSITE</a> — Look up the motifs identified to understand what biological function they may be associated with.
        </li>
        <li>
            <a href="https://blast.ncbi.nlm.nih.gov/Blast.cgi?PAGE=Proteins" target="_blank">NCBI BLASTP</a> — Paste in a sequence from your FASTA file to search for similar proteins across all organisms.
        </li>
    </ul>
    <p>These tools can help you interpret your results or plan further analysis.</p>
</div>
_EXTRAS;


echo "<p style='margin-top: 30px;'><a href='index.php'>⬅️ Back to Homepage</a></p>";
echo "</div>";
$pageContent = ob_get_clean();
$pageTitle = "Search Results for $protein ($taxon)";
include './features/base_layout.php';
?>